force-app/main/default/objects/DemoQuestion__c/DemoQuestion__c.object-meta.xml
<CustomObject>
    <label>DemoQuestion</label>
    <nameField>
        <label>DemoQuestion Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DemoQuestions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/DemoResult__c/DemoResult__c.object-meta.xml
<CustomObject>
    <label>Demo Result</label>
    <nameField>
        <label>DemoResult Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Demo Results</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/DemoResult__c/fields/DemoQuestion__c.field-meta.xml
<CustomField>
    <fullName>DemoQuestion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DemoQuestion</label>
    <referenceTo>DemoQuestion__c</referenceTo>
    <relationshipLabel>Demo Results</relationshipLabel>
    <relationshipName>Demo_Results1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Triggers/ResultTriggerHandler.cls
public with sharing class ResultTriggerHandler extends TriggerHandler{
    public ResultTriggerHandler(){
        super('DemoResult__c');
    }
    
    public override void beforeInsert(List<sObject> listNewItems){
        disableDoubleVoting(listNewItems); 
        
    }
    
    public  void disableDoubleVoting(List<sObject> listNewItems){
        
      
            String userID = UserInfo.getUserId();
            Map<id,DemoResult__c> demoQuestionIdsToDemoResult = new  Map<id,DemoResult__c>(); 
      
            for(DemoResult__c d : (List<DemoResult__c>)listNewItems) {
                demoQuestionIdsToDemoResult.put(d.DemoQuestion__c, d);
            }
            
            for(DemoResult__c existingAnswer: [SELECT DemoQuestion__c FROM DemoResult__c WHERE Owner.Id =:userID AND DemoQuestion__c IN :demoQuestionIdsToDemoResult.keySet() ]){
                demoQuestionIdsToDemoResult.get(existingAnswer.DemoQuestion__c).addError('You\'re only allowed to vote once for each question');   
                
            }
        
   
    }
}