force-app/main/default/objects/DemoAnswer__c/DemoAnswer__c.object-meta.xml
<CustomObject>
    <label>DemoAnswer</label>
    <nameField>
        <label>DemoAnswer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DemoAnswers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DemoAnswer__c/fields/DemoQuestion__c.field-meta.xml
<CustomField>
    <fullName>DemoQuestion__c</fullName>
    <label>DemoQuestion</label>
    <referenceTo>DemoQuestion__c</referenceTo>
    <relationshipLabel>DemoAnswers</relationshipLabel>
    <relationshipName>DemoAnswers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DemoCampaign__c/DemoCampaign__c.object-meta.xml
<CustomObject>
    <label>DemoCampaign</label>
    <nameField>
        <label>DemoCampaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DemoCampaigns</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/DemoCampaign__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>In progress</fullName>
            </value>
            <value>
                <fullName>Paused</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DemoQuestion__c/DemoQuestion__c.object-meta.xml
<CustomObject>
    <label>DemoQuestion</label>
    <nameField>
        <label>DemoQuestion Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DemoQuestions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/DemoQuestion__c/fields/DemoCampaign__c.field-meta.xml
<CustomField>
    <fullName>DemoCampaign__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>DemoCampaign</label>
    <referenceTo>DemoCampaign__c</referenceTo>
    <relationshipLabel>DemoQuestions</relationshipLabel>
    <relationshipName>DemoVotings</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DemoResult__c/DemoResult__c.object-meta.xml
<CustomObject>
    <label>Demo Result</label>
    <nameField>
        <label>DemoResult Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Demo Results</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/DemoResult__c/fields/DemoAnswer__c.field-meta.xml
<CustomField>
    <fullName>DemoAnswer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DemoAnswer</label>
    <referenceTo>DemoAnswer__c</referenceTo>
    <relationshipLabel>Demo Results</relationshipLabel>
    <relationshipName>Demo_Results1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DemoResult__c/fields/DemoCampaign__c.field-meta.xml
<CustomField>
    <fullName>DemoCampaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DemoCampaign</label>
    <referenceTo>DemoCampaign__c</referenceTo>
    <relationshipLabel>Demo Results</relationshipLabel>
    <relationshipName>Demo_Results1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DemoResult__c/fields/DemoQuestion__c.field-meta.xml
<CustomField>
    <fullName>DemoQuestion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DemoQuestion</label>
    <referenceTo>DemoQuestion__c</referenceTo>
    <relationshipLabel>Demo Results</relationshipLabel>
    <relationshipName>Demo_Results1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/voterClasses/VoterHandler.cls
public with sharing class VoterHandler {
    


    @AuraEnabled(cacheable=true)
    public static List<sObject> getAnswersList(String questionId) {
        return [SELECT Id, Name FROM DemoAnswer__c WHERE DemoQuestion__c =:questionId WITH SECURITY_ENFORCED];
    }


    @AuraEnabled(cacheable = true)
    public static List<sObject> getQuestionsList(String campaignId) {
        return [SELECT Id, Name FROM DemoQuestion__c WHERE Id NOT IN (SELECT DemoQuestion__c FROM DemoResult__c) AND DemoCampaign__r.Id =:campaignId WITH SECURITY_ENFORCED];
    }


    
    @AuraEnabled(cacheable=true)
    public static List<sObject> getCampaignsList() {
        return [SELECT Id, Name FROM DemoCampaign__c WHERE Status__c= 'In progress' WITH SECURITY_ENFORCED];

}
}