force-app/main/default/objects/DemoAnswer__c/DemoAnswer__c.object-meta.xml
<CustomObject>
    <label>DemoAnswer</label>
    <nameField>
        <label>DemoAnswer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DemoAnswers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DemoAnswer__c/fields/DemoQuestion__c.field-meta.xml
<CustomField>
    <fullName>DemoQuestion__c</fullName>
    <label>DemoQuestion</label>
    <referenceTo>DemoQuestion__c</referenceTo>
    <relationshipLabel>DemoAnswers</relationshipLabel>
    <relationshipName>DemoAnswers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DemoCampaign__c/DemoCampaign__c.object-meta.xml
<CustomObject>
    <label>DemoCampaign</label>
    <nameField>
        <label>DemoCampaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DemoCampaigns</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/DemoCampaign__c/fields/DemoLocation__c.field-meta.xml
<CustomField>
    <fullName>DemoLocation__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>DemoLocation</label>
    <referenceTo>DemoLocation__c</referenceTo>
    <relationshipLabel>DemoCampaigns</relationshipLabel>
    <relationshipName>DemoCampaigns</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DemoCampaign__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>In progress</fullName>
            </value>
            <value>
                <fullName>Paused</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DemoLocation__c/DemoLocation__c.object-meta.xml
<CustomObject>
    <label>DemoLocation</label>
    <nameField>
        <label>DemoLocation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DemoLocations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DemoLocation__c/fields/DemoCampaign__c.field-meta.xml
<CustomField>
    <fullName>DemoCampaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DemoCampaign</label>
    <referenceTo>DemoCampaign__c</referenceTo>
    <relationshipLabel>DemoLocations</relationshipLabel>
    <relationshipName>DemoLocations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DemoQuestion__c/DemoQuestion__c.object-meta.xml
<CustomObject>
    <label>DemoQuestion</label>
    <nameField>
        <label>DemoQuestion Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DemoQuestions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/DemoQuestion__c/fields/DemoCampaign__c.field-meta.xml
<CustomField>
    <fullName>DemoCampaign__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>DemoCampaign</label>
    <referenceTo>DemoCampaign__c</referenceTo>
    <relationshipLabel>DemoQuestions</relationshipLabel>
    <relationshipName>DemoVotings</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DemoQuestion__c/fields/DemoLocation__c.field-meta.xml
<CustomField>
    <fullName>DemoLocation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DemoLocation</label>
    <referenceTo>DemoLocation__c</referenceTo>
    <relationshipLabel>DemoQuestions</relationshipLabel>
    <relationshipName>DemoQuestions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/voterClasses/VoterHandlerTest.cls
@isTest
public with sharing class VoterHandlerTest {
    @isTest static void campaignsListTest() {
        Test.startTest(); 
        Integer sizeBefore = VoterHandler.getCampaignsList().size(); 
        DemoCampaign__c testCamp = new DemoCampaign__c(
        Name = 'Test3',
        DemoLocation__c='a057R000016fnrfQAA',
        Status__c='In progress'
        );
        insert testCamp; 
        Integer sizeAfter = VoterHandler.getCampaignsList().size(); 
        Test.stopTest(); 
        System.assert(sizeAfter == (sizeBefore +1 ));
    }

    @isTest static void questionsListTest() {
        Test.startTest(); 
        Integer sizeBefore = VoterHandler.getQuestionsList('a007R000010bc6nQAA').size(); 
        DemoQuestion__c testCamp = new DemoQuestion__c(
        Name = 'Test4',
        DemoCampaign__c='a007R000010bc6nQAA'
        );
        insert testCamp; 
        Integer sizeAfter = VoterHandler.getQuestionsList('a007R000010bc6nQAA').size();  
        Test.stopTest(); 
        System.assert(sizeAfter == (sizeBefore +1 ));
    }

    @isTest static void answersListTest() {
        Test.startTest(); 
        Integer sizeBefore = VoterHandler.getAnswersList('a017R00004AEwBCQA1').size(); 
        DemoAnswer__c testCamp = new DemoAnswer__c(
        Name = 'Test5',
        DemoQuestion__c='a017R00004AEwBCQA1'
        );
        insert testCamp; 
        Integer sizeAfter = VoterHandler.getAnswersList('a017R00004AEwBCQA1').size();  
        Test.stopTest(); 
        System.assert(sizeAfter == (sizeBefore +1 ));

    }
}