force-app/main/default/objects/DemoAnswer__c/DemoAnswer__c.object-meta.xml
<CustomObject>
    <label>DemoAnswer</label>
    <nameField>
        <label>DemoAnswer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DemoAnswers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DemoAnswer__c/fields/DemoQuestion__c.field-meta.xml
<CustomField>
    <fullName>DemoQuestion__c</fullName>
    <label>DemoQuestion</label>
    <referenceTo>DemoQuestion__c</referenceTo>
    <relationshipLabel>DemoAnswers</relationshipLabel>
    <relationshipName>DemoAnswers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DemoQuestion__c/DemoQuestion__c.object-meta.xml
<CustomObject>
    <label>DemoQuestion</label>
    <nameField>
        <label>DemoQuestion Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DemoQuestions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/DemoResult__c/DemoResult__c.object-meta.xml
<CustomObject>
    <label>Demo Result</label>
    <nameField>
        <label>DemoResult Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Demo Results</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/DemoResult__c/fields/DemoAnswer__c.field-meta.xml
<CustomField>
    <fullName>DemoAnswer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DemoAnswer</label>
    <referenceTo>DemoAnswer__c</referenceTo>
    <relationshipLabel>Demo Results</relationshipLabel>
    <relationshipName>Demo_Results1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DemoResult__c/fields/DemoQuestion__c.field-meta.xml
<CustomField>
    <fullName>DemoQuestion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DemoQuestion</label>
    <referenceTo>DemoQuestion__c</referenceTo>
    <relationshipLabel>Demo Results</relationshipLabel>
    <relationshipName>Demo_Results1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Reports/ReportLogic.cls
public without sharing class ReportLogic {
   
    @AuraEnabled(cacheable = true)
     public static Map < String, Decimal > getResultsByQuestions(String questionId) {
        List <AggregateResult> countedVotes = [SELECT Count(Name) votesAmount, DemoAnswer__r.Name answers FROM DemoResult__c WHERE DemoQuestion__c =:questionId GROUP BY DemoAnswer__r.Name ];
        Map <String, Decimal> wrap = new Map < String, Decimal > ();

        for (AggregateResult voteStatistic: countedVotes) {
            wrap.put(String.valueOf(voteStatistic.get('answers')), (Decimal) voteStatistic.get('votesAmount'));
        }
        
        return wrap;
    }
}