force-app/main/default/objects/DemoAnswer__c/DemoAnswer__c.object-meta.xml
<CustomObject>
    <label>DemoAnswer</label>
    <nameField>
        <label>DemoAnswer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DemoAnswers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DemoAnswer__c/fields/DemoQuestion__c.field-meta.xml
<CustomField>
    <fullName>DemoQuestion__c</fullName>
    <label>DemoQuestion</label>
    <referenceTo>DemoQuestion__c</referenceTo>
    <relationshipLabel>DemoAnswers</relationshipLabel>
    <relationshipName>DemoAnswers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DemoQuestion__c/DemoQuestion__c.object-meta.xml
<CustomObject>
    <label>DemoQuestion</label>
    <nameField>
        <label>DemoQuestion Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DemoQuestions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/DemoResult__c/DemoResult__c.object-meta.xml
<CustomObject>
    <label>Demo Result</label>
    <nameField>
        <label>DemoResult Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Demo Results</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/DemoResult__c/fields/DemoAnswer__c.field-meta.xml
<CustomField>
    <fullName>DemoAnswer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DemoAnswer</label>
    <referenceTo>DemoAnswer__c</referenceTo>
    <relationshipLabel>Demo Results</relationshipLabel>
    <relationshipName>Demo_Results1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DemoResult__c/fields/DemoCampaign_del__c.field-meta.xml
<CustomField>
    <fullName>DemoCampaign_del__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DemoCampaign</label>
    <referenceTo>DemoCampaign__c</referenceTo>
    <relationshipLabel>Demo Results</relationshipLabel>
    <relationshipName>Demo_Results1_del</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DemoResult__c/fields/DemoQuestion__c.field-meta.xml
<CustomField>
    <fullName>DemoQuestion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DemoQuestion</label>
    <referenceTo>DemoQuestion__c</referenceTo>
    <relationshipLabel>Demo Results</relationshipLabel>
    <relationshipName>Demo_Results1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/voterClasses/Event.cls
public class Event{
    @AuraEnabled()
      public static void addNewResult(String Name, String Campaign, String Question, String Answer){
        String msg = '';
        try {
            DemoResult__c result = new DemoResult__c();
            result.Name = Name; 
            result.DemoCampaign_del__c = Campaign; 
            result.DemoQuestion__c = Question;
            result.DemoAnswer__c = Answer; 
            insert result;

        }catch(DmlException e){
        
            for (Integer i = 0; i < e.getNumDml(); i++) {
                
                msg =+ e.getDmlMessage(i) +  '\n' ;
            }
            
            throw new AuraHandledException(msg);
            
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
        
    }
    
}