force-app/main/default/objects/DemoAnswer__c/DemoAnswer__c.object-meta.xml
<CustomObject>
    <label>DemoAnswer</label>
    <nameField>
        <label>DemoAnswer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DemoAnswers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DemoAnswer__c/fields/DemoQuestion__c.field-meta.xml
<CustomField>
    <fullName>DemoQuestion__c</fullName>
    <label>DemoQuestion</label>
    <referenceTo>DemoQuestion__c</referenceTo>
    <relationshipLabel>DemoAnswers</relationshipLabel>
    <relationshipName>DemoAnswers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DemoQuestion__c/DemoQuestion__c.object-meta.xml
<CustomObject>
    <label>DemoQuestion</label>
    <nameField>
        <label>DemoQuestion Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DemoQuestions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/DemoResult__c/DemoResult__c.object-meta.xml
<CustomObject>
    <label>Demo Result</label>
    <nameField>
        <label>DemoResult Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Demo Results</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/DemoResult__c/fields/DemoAnswer__c.field-meta.xml
<CustomField>
    <fullName>DemoAnswer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DemoAnswer</label>
    <referenceTo>DemoAnswer__c</referenceTo>
    <relationshipLabel>Demo Results</relationshipLabel>
    <relationshipName>Demo_Results1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DemoResult__c/fields/DemoCampaign_del__c.field-meta.xml
<CustomField>
    <fullName>DemoCampaign_del__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DemoCampaign</label>
    <referenceTo>DemoCampaign__c</referenceTo>
    <relationshipLabel>Demo Results</relationshipLabel>
    <relationshipName>Demo_Results1_del</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DemoResult__c/fields/DemoQuestion__c.field-meta.xml
<CustomField>
    <fullName>DemoQuestion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DemoQuestion</label>
    <referenceTo>DemoQuestion__c</referenceTo>
    <relationshipLabel>Demo Results</relationshipLabel>
    <relationshipName>Demo_Results1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Triggers/ResultTriggerHandlerTest.cls
@isTest
public with sharing class ResultTriggerHandlerTest {
    @isTest static void ResultTriggerHandlerTest() {     
        Test.startTest();
        DemoResult__c result = new DemoResult__c();
        result.Name = 'TestResult'; 
        result.DemoCampaign_del__c = 'a007R000010bc6nQAA'; 
        result.DemoQuestion__c = 'a017R00004AEwBCQA1';
        result.DemoAnswer__c = 'a027R00000qlQ1lQAE'; 
        insert result;

        try{
        DemoResult__c duplicate = new DemoResult__c();
        duplicate.Name = 'TestResult2'; 
        duplicate.DemoCampaign_del__c = 'a007R000010bc6nQAA'; 
        duplicate.DemoQuestion__c = 'a017R00004AEwBCQA1';
        duplicate.DemoAnswer__c = 'a027R00000qlQ1lQAE'; 
            insert duplicate; 
        } catch (Exception e){
            System.assertEquals('You\'re only allowed to vote once for each question',
        e.getMessage());
        }
    
        Test.stopTest();
    }
}