force-app/main/default/objects/DemoCampaign__c/DemoCampaign__c.object-meta.xml
<CustomObject>
    <label>DemoCampaign</label>
    <nameField>
        <label>DemoCampaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DemoCampaigns</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/DemoCampaign__c/fields/DemoLocation__c.field-meta.xml
<CustomField>
    <fullName>DemoLocation__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>DemoLocation</label>
    <referenceTo>DemoLocation__c</referenceTo>
    <relationshipLabel>DemoCampaigns</relationshipLabel>
    <relationshipName>DemoCampaigns</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DemoLocation__c/DemoLocation__c.object-meta.xml
<CustomObject>
    <label>DemoLocation</label>
    <nameField>
        <label>DemoLocation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DemoLocations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DemoLocation__c/fields/DemoCampaign__c.field-meta.xml
<CustomField>
    <fullName>DemoCampaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DemoCampaign</label>
    <referenceTo>DemoCampaign__c</referenceTo>
    <relationshipLabel>DemoLocations</relationshipLabel>
    <relationshipName>DemoLocations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Triggers/CampaignTriggerHandlerTest.cls
@isTest
public with sharing class CampaignTriggerHandlerTest {
    
    @isTest static void CampaignTriggerHandlerTest() {
        DemoCampaign__c result = new DemoCampaign__c();
        result.Name = 'Name1'; 
        result.DemoLocation__c = 'a057R000016fnrfQAA'; 
        insert result; 

        Test.startTest(); 
        try{
            DemoCampaign__c duplicateName = new DemoCampaign__c();
            duplicateName.Name = 'Name1'; 
            duplicateName.DemoLocation__c = 'a057R000016fnrfQAA'; 
        insert duplicateName; 

        } catch (Exception e){
            System.assertEquals('Insert failed. First exception on row 0; first error: FIELD_CUSTOM_VALIDATION_EXCEPTION, Campaign with this name already exists: []',
        e.getMessage());
        }
    
        Test.stopTest();

    }
}