force-app/main/default/objects/DemoCampaign__c/DemoCampaign__c.object-meta.xml
<CustomObject>
    <label>DemoCampaign</label>
    <nameField>
        <label>DemoCampaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DemoCampaigns</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/DemoQuestion__c/DemoQuestion__c.object-meta.xml
<CustomObject>
    <label>DemoQuestion</label>
    <nameField>
        <label>DemoQuestion Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DemoQuestions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/DemoQuestion__c/fields/DemoCampaign__c.field-meta.xml
<CustomField>
    <fullName>DemoCampaign__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>DemoCampaign</label>
    <referenceTo>DemoCampaign__c</referenceTo>
    <relationshipLabel>DemoQuestions</relationshipLabel>
    <relationshipName>DemoVotings</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Reports/ReportController.cls
public with sharing class ReportController {

    @AuraEnabled(cacheable = true)
    public static List<sObject> getAnsweredQuestions(String campaignId) {
        return [SELECT Name FROM DemoQuestion__c WHERE DemoCampaign__c=:campaignId];
    }
    
    @AuraEnabled(cacheable=true)
    public static List<sObject> getAnsweredCampaigns() {
        return [SELECT Name FROM DemoCampaign__c WITH SECURITY_ENFORCED];
}
}