force-app/main/default/objects/DemoCampaign__c/DemoCampaign__c.object-meta.xml
<CustomObject>
    <label>DemoCampaign</label>
    <nameField>
        <label>DemoCampaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DemoCampaigns</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/DemoCampaign__c/fields/DemoLocation__c.field-meta.xml
<CustomField>
    <fullName>DemoLocation__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>DemoLocation</label>
    <referenceTo>DemoLocation__c</referenceTo>
    <relationshipLabel>DemoCampaigns</relationshipLabel>
    <relationshipName>DemoCampaigns</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DemoLocation__c/DemoLocation__c.object-meta.xml
<CustomObject>
    <label>DemoLocation</label>
    <nameField>
        <label>DemoLocation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DemoLocations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DemoLocation__c/fields/DemoCampaign__c.field-meta.xml
<CustomField>
    <fullName>DemoCampaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DemoCampaign</label>
    <referenceTo>DemoCampaign__c</referenceTo>
    <relationshipLabel>DemoLocations</relationshipLabel>
    <relationshipName>DemoLocations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DemoQuestion__c/DemoQuestion__c.object-meta.xml
<CustomObject>
    <label>DemoQuestion</label>
    <nameField>
        <label>DemoQuestion Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DemoQuestions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/DemoQuestion__c/fields/DemoCampaign__c.field-meta.xml
<CustomField>
    <fullName>DemoCampaign__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>DemoCampaign</label>
    <referenceTo>DemoCampaign__c</referenceTo>
    <relationshipLabel>DemoQuestions</relationshipLabel>
    <relationshipName>DemoVotings</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DemoQuestion__c/fields/DemoLocation__c.field-meta.xml
<CustomField>
    <fullName>DemoLocation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DemoLocation</label>
    <referenceTo>DemoLocation__c</referenceTo>
    <relationshipLabel>DemoQuestions</relationshipLabel>
    <relationshipName>DemoQuestions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Reports/ReportControllerTest.cls
@isTest
public with sharing class ReportControllerTest {
    
    @isTest static void getCampaignsTest() {
    test.startTest(); 
        Integer sizeBefore = ReportController.getAnsweredCampaigns().size(); 
        DemoCampaign__c dc = new DemoCampaign__c();
        dc.Name='Test1';
        dc.DemoLocation__c = 'a057R000016fnrfQAA';
        insert dc; 
        Integer sizeAfter = ReportController.getAnsweredCampaigns().size(); 
    test.stopTest(); 
        System.assert(sizeAfter == (sizeBefore +1 ));
    }

    @isTest static void getQuestionstest() {
    test.startTest(); 
        Integer sizeBefore = ReportController.getAnsweredQuestions('a007R000010bc6nQAA').size();
        DemoQuestion__c dc = new DemoQuestion__c();
        dc.Name='Test2';
        dc.DemoCampaign__c = 'a007R000010bc6nQAA';
        insert dc; 
        Integer sizeAfter = ReportController.getAnsweredQuestions('a007R000010bc6nQAA').size(); 
    test.stopTest(); 
        System.assert(sizeAfter == (sizeBefore +1 ));

    }
}